version: '3.8'

services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
  uba-bot:
    image: totomc/dc-uba-bot:1.1
    container_name: dc-uba-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-db
volumes:
  mongodb_data:
